const fs = require('fs');

const uz = {
  nav: { home: "Bosh sahifa", about: "Biz haqimizda", tours: "Turlar", contacts: "Aloqa" },
  footer: { desc: "Sizning orzuingizdagi ta'tilni biz bilan rejalashtiring. Dunyo bo'ylab eng yaxshi va hamyonbop sayohatlar.", links: "Tezkor havolalar", contact: "Aloqa", rights: "Barcha huquqlar himoyalangan." },
  hero: { slide1_title: "Dunyo bo'ylab unutilmas sayohatlar", slide1_sub: "Sizning orzuingizdagi ta'til endi yanada yaqinroq", slide2_title: "Maldiv orollarida hordiq", slide2_sub: "Kristaldek toza suvlar va oq qumli plyajlar", slide3_title: "Yevropa bo'ylab tur", slide3_sub: "Tarix va zamonaviylik uyg'unligi", btn_more: "Batafsil", btn_book: "Buyurtma berish" },
  tours: { subtitle: "Bizning takliflar", title: "Haftalik Turlar", desc: "Eng sara va arzon narxlardagi sayohat paketlarimiz bilan tanishing. Siz uchun maxsus tayyorlangan dasturlar.", from: "dan", details: "Batafsil ma'lumot", load_more: "Yana ko'rish", close: "Yopish" },
  visa: { subtitle: "Viza Xizmatlari", title: "Dunyo bo'ylab vizalar", desc: "Viza olishdagi qiyinchiliklarni bizga topshiring. Professional jamoamiz hujjatlaringizni 100% to'g'ri tayyorlaydi.", apply: "Ariza qoldirish", load_more: "Yana ko'rish", close: "Yopish" },
  contact: { subtitle: "Aloqa", title: "Biz bilan bog'laning", desc: "Savollaringiz bormi? Mutaxassislarimiz sizga yordam berishdan xursand bo'lishadi.", address: "Bizning manzil", address_val: "Toshkent shahri, Amir Temur ko'chasi 108-uy", phone: "Telefon", email: "Elektron pochta", form_title: "Ariza qoldirish", form_name: "Ismingiz", form_name_ph: "Falonchi Pistonchiyev", form_phone: "Telefon raqamingiz", form_msg: "Xabar", form_msg_ph: "Savol yoki taklifingizni yozing...", submit: "Yuborish", success: "Arizangiz qabul qilindi! Tez orada aloqaga chiqamiz." },
  detail: { premium: "Premium Tour", about: "Sayohat haqida", includes: "Narxga kiradi", excludes: "Narxga kirmaydi", itinerary: "Kunlik Dastur", gallery: "Galereya", price_title: "Sayohat Narxi", per_person: "/ kishi boshiga", duration: "Davomiylik", date: "Sana", apply: "Ariza qoldirish", apply_desc: "Biz siz bilan tez fursatda bog'lanamiz", book: "Band qilish", book_desc: "Ma'lumotlaringizni qoldiring, mutaxassislarimiz sizga tezda aloqaga chiqishadi.", loading: "Yuklanmoqda..." },
  visas_data: [
    { country: 'Yaponiya', flag: '🇯🇵', price: '$150', features: ['Turistik viza', '15 kungacha', 'Hujjatlarni tayyorlash', 'Suhbatga yozish'] },
    { country: 'Saudiya Arabistoni', flag: '🇸🇦', price: '$200', features: ['Umra vizasi', '1 yil muddatli', 'Elektron viza', 'Tezkor rasmiylashtirish'] },
    { country: 'Shengen', flag: '🇪🇺', price: '$120', features: ['Turistik viza', 'Ko\'p martalik', 'Sug\'urta qamrovi', 'Viza markazida hamrohlik'] },
    { country: 'Dubay (BAA)', flag: '🇦🇪', price: '$90', features: ['Elektron viza', '30 kunlik', '3 kun ichida tayyor', 'Kafil kerak emas'] },
    { country: 'AQSH', flag: '🇺🇸', price: '$300', features: ['B1/B2 vizasi', '10 yillik', 'Anketa to\'ldirish', 'Suhbatga yozish'] },
    { country: 'Buyuk Britaniya', flag: '🇬🇧', price: '$250', features: ['Standard Visitor', '6 oylik', 'Hujjatlarni tarjima qilish', 'Konsullik ro\'yxatidan o\'tish'] }
  ],
  tours_data: {
    t1: { title: "Dubay mo'jizalari", location: "Birlashgan Arab Amirliklari", days: "5 kun / 4 kecha", date: "Har hafta", description: "Dubayning eng mashhur joylari, Burj Xalifa, Jumeirah plyaji va ajoyib cho'l safarisidan iborat to'liq paket.", includes: ["Aviachipta", "4 yulduzli mehmonxona", "Nonushta", "Transfer", "Viza yordami"], excludes: ["Tushlik va kechki ovqat", "Shaxsiy xarajatlar"], itinerary: [{day:1,title:"Kelish",desc:"Aeroportda kutib olish va joylashish."}, {day:2,title:"Ekskursiya",desc:"Burj Xalifa va Dubai Mall."}, {day:3,title:"Cho'l safarisi",desc:"Jip safari va barbekyu."}, {day:4,title:"Erkin kun",desc:"Marina plyajida dam olish."}, {day:5,title:"Qaytish",desc:"Aeroportga transfer."}] },
    t2: { title: "Antaliya dam olishi", location: "Turkiya", days: "7 kun / 6 kecha", date: "Iyun - Avgust", description: "O'rta dengiz sohillarida unutilmas hordiq. Barcha qulayliklarga ega 5 yulduzli mehmonxonalar.", includes: ["Aviachipta", "5* UAI Mehmonxona", "Barcha ovqatlanish", "Transfer", "Sug'urta"], excludes: ["Shaxsiy xarajatlar", "Qo'shimcha turlar"], itinerary: [{day:1,title:"Kelish",desc:"Kutib olish va plyaj bilan tanishish."}, {day:"2-6",title:"Dam olish",desc:"Dengiz sohilida erkin dam olish."}, {day:7,title:"Qaytish",desc:"Aeroportga transfer."}] },
    t3: { title: "Parij romantikasi", location: "Fransiya", days: "6 kun / 5 kecha", date: "Kuz mavsumi", description: "Eyfel minorasi, Luvr va Sena daryosi. Sevishganlar uchun eng yaxshi taklif.", includes: ["Aviachipta", "Mehmonxona", "Ekskursiya", "Viza ko'magi"], excludes: ["Ovqatlanish", "Muzey chiptalari"], itinerary: [{day:1,title:"Kelish",desc:"Joylashish va shahar sayri."}, {day:2,title:"Eyfel",desc:"Minoraga chiqish va kema sayri."}, {day:3,title:"Luvr",desc:"Luvr muzeyiga tashrif."}, {day:"4-5",title:"Erkin kun",desc:"Xaridlar va dam olish."}, {day:6,title:"Qaytish",desc:"Aeroportga transfer."}] },
    t4: { title: "Misr ehromlari", location: "Misr", days: "6 kun / 5 kecha", date: "Oktyabr - Aprel", description: "Qadimiy tarix va Qizil dengiz sohilidagi ajoyib dam olish.", includes: ["Aviachipta", "5* mehmonxona", "Hammasi kiritilgan", "Transfer"], excludes: ["Qohira ekskursiyasi", "Viza"], itinerary: [{day:1,title:"Kelish",desc:"Mehmonxonaga joylashish."}, {day:2,title:"Dengiz",desc:"Yaxtada sayr va dayving."}, {day:3,title:"Erkin kun",desc:"Qohiraga ixtiyoriy sayohat."}, {day:4,title:"Cho'l safari",desc:"Kvadrotsikllarda safar."}, {day:5,title:"Qaytish",desc:"Uchish."}] },
    t5: { title: "Makka va Madina ziyori", location: "Saudiya Arabistoni", days: "14 kun / 13 kecha", date: "Har oy", description: "Umra ziyorati uchun to'liq paket. Madinada 3 kun, Makkada 10 kun.", includes: ["Aviachipta", "Mehmonxonalar", "Ikki mahal ovqat", "Viza", "Ellikboshi"], excludes: ["Shaxsiy xarajatlar"], itinerary: [{day:1,title:"Madina",desc:"Joylashish va Masjid an-Nabaviy."}, {day:"2-3",title:"Ziyoratlar",desc:"Quba, Uhud tog'i."}, {day:4,title:"Makkaga yo'l",desc:"Umra amalini bajarish."}, {day:"5-13",title:"Makka",desc:"Makka ziyoratgohlari va toat-ibodat."}, {day:14,title:"Qaytish",desc:"Toshkentga parvoz."}] },
    t6: { title: "Istanbul sayohati", location: "Turkiya", days: "5 kun / 4 kecha", date: "Har hafta", description: "Ikki qit'ani birlashtirgan tarixiy shahar bo'ylab ajoyib sayohat.", includes: ["Aviachipta", "4* mehmonxona", "Nonushta", "Transfer", "Ekskursiya"], excludes: ["Muzey chiptalari"], itinerary: [{day:1,title:"Kelish",desc:"Mehmonxonaga joylashish."}, {day:2,title:"Tarixiy Istanbul",desc:"Aya Sofiya va Moviy masjid."}, {day:3,title:"Bosfor",desc:"Bosfor bo'g'ozida kema sayri."}, {day:4,title:"Erkin kun",desc:"Kapali Charshi bozorida xaridlar."}, {day:5,title:"Qaytish",desc:"Transfer."}] },
    t7: { title: "Tailand sarguzashtlari", location: "Tailand", days: "8 kun / 7 kecha", date: "Qish mavsumi", description: "Egzotik tabiat, fillar va budda ibodatxonalari.", includes: ["Aviachipta", "Mehmonxona", "Nonushta", "Transfer"], excludes: ["Viza to'lovi"], itinerary: [{day:1,title:"Kelish",desc:"Joylashish."}, {day:"2-7",title:"Ekskursiyalar",desc:"Orollarga sayohat."}, {day:8,title:"Qaytish",desc:"Uchish."}] },
    t8: { title: "Kapadokiya osmoni", location: "Turkiya", days: "4 kun / 3 kecha", date: "Mavsumiy", description: "G'orlardagi mehmonxonalar va havo sharlarida unutilmas parvoz.", includes: ["Ichki parvoz", "G'or mehmonxona", "Nonushta"], excludes: ["Havo sharida uchish"], itinerary: [{day:1,title:"Kelish",desc:"Transfer."}, {day:2,title:"Qizil tur",desc:"Uchhisar qal'asi."}, {day:3,title:"Havo shari",desc:"Tongida havo sharlarida uchish."}, {day:4,title:"Qaytish",desc:"Transfer."}] },
    t9: { title: "Singapur va Malayziya", location: "Osiyo", days: "8 kun / 7 kecha", date: "Har oy", description: "Osiyoning eng zamonaviy shaharlari bo'ylab sayohat.", includes: ["Aviachipta", "4* Mehmonxonalar", "Nonushta", "Ekskursiya"], excludes: ["Viza", "Shaxsiy xarajatlar"], itinerary: [{day:1,title:"Kuala Lumpur",desc:"Kutib olish."}, {day:2,title:"G'orlar",desc:"Batu g'orlari."}, {day:3,title:"Singapur",desc:"Singapurga o'tish."}, {day:4,title:"Marina Bay",desc:"Gardens by the Bay."}, {day:"5-7",title:"Erkin",desc:"Sentosa oroli."}, {day:8,title:"Qaytish",desc:"Parvoz."}] },
    t10: { title: "Gruziya sarguzashtlari", location: "Gruziya", days: "6 kun / 5 kecha", date: "Bahor va Kuz", description: "Kavkaz tog'lari, qadimiy cherkovlar va mazali taomlar.", includes: ["Aviachipta", "Mehmonxona", "Nonushta", "Gid"], excludes: ["Ovqatlanish"], itinerary: [{day:1,title:"Tbilisi",desc:"Kelish."}, {day:2,title:"Shahar",desc:"Eski shahar sayri."}, {day:3,title:"Kazbegi",desc:"Kavkaz tog'lari."}, {day:4,title:"Mtsxeta",desc:"Qadimiy poytaxt."}, {day:5,title:"Erkin",desc:"Xaridlar."}, {day:6,title:"Qaytish",desc:"Transfer."}] },
    t11: { title: "Boku go'zalligi", location: "Ozarbayjon", days: "4 kun / 3 kecha", date: "Har oy", description: "Olovlar yurti Ozarbayjon poytaxti Boku.", includes: ["Aviachipta", "Mehmonxona", "Nonushta"], excludes: ["Ekskursiyalar"], itinerary: [{day:1,title:"Kelish",desc:"Joylashish."}, {day:2,title:"Eski shahar",desc:"Qiz qal'asi."}, {day:3,title:"Boku",desc:"Olovli minoralar."}, {day:4,title:"Qaytish",desc:"Transfer."}] },
    t12: { title: "Italiya va Shveysariya", location: "Yevropa", days: "9 kun / 8 kecha", date: "Yoz mavsumi", description: "Rim, Venetsiya, Milan va Alp tog'lari bo'ylab Yevropa turnesi.", includes: ["Aviachipta", "Mehmonxona", "Nonushta", "Poyezd", "Viza"], excludes: ["Ovqatlanish"], itinerary: [{day:1,title:"Rim",desc:"Kelish."}, {day:2,title:"Kolizey",desc:"Tarixiy Rim."}, {day:3,title:"Florensiya",desc:"Poyezdda o'tish."}, {day:4,title:"Venetsiya",desc:"Gondolada sayr."}, {day:5,title:"Milan",desc:"Duomo."}, {day:"6-8",title:"Alp",desc:"Shveysariya manzaralari."}, {day:9,title:"Qaytish",desc:"Uchish."}] }
  }
};

const ru = {
  nav: { home: "Главная", about: "О нас", tours: "Туры", contacts: "Контакты" },
  footer: { desc: "Спланируйте отпуск своей мечты вместе с нами. Лучшие и доступные туры по всему миру.", links: "Быстрые ссылки", contact: "Контакты", rights: "Все права защищены." },
  hero: { slide1_title: "Незабываемые путешествия по миру", slide1_sub: "Ваш отпуск мечты теперь еще ближе", slide2_title: "Отдых на Мальдивах", slide2_sub: "Кристально чистые воды и белые песчаные пляжи", slide3_title: "Тур по Европе", slide3_sub: "Гармония истории и современности", btn_more: "Подробнее", btn_book: "Забронировать" },
  tours: { subtitle: "Наши предложения", title: "Еженедельные туры", desc: "Ознакомьтесь с нашими лучшими и доступными путевками. Программы, созданные специально для вас.", from: "от", details: "Подробная информация", load_more: "Показать еще", close: "Закрыть" },
  visa: { subtitle: "Визовые услуги", title: "Визы по всему миру", desc: "Доверьте нам сложности получения визы. Наша профессиональная команда подготовит ваши документы на 100% правильно.", apply: "Оставить заявку", load_more: "Показать еще", close: "Закрыть" },
  contact: { subtitle: "Контакты", title: "Свяжитесь с нами", desc: "У вас есть вопросы? Наши специалисты будут рады вам помочь.", address: "Наш адрес", address_val: "г. Ташкент, ул. Амира Темура, 108", phone: "Телефон", email: "Электронная почта", form_title: "Оставить заявку", form_name: "Ваше имя", form_name_ph: "Иван Иванов", form_phone: "Ваш номер телефона", form_msg: "Сообщение", form_msg_ph: "Напишите ваш вопрос или предложение...", submit: "Отправить", success: "Ваша заявка принята! Мы скоро свяжемся с вами." },
  detail: { premium: "Премиум тур", about: "О туре", includes: "Включено в стоимость", excludes: "Не включено", itinerary: "Программа", gallery: "Галерея", price_title: "Стоимость", per_person: "/ за человека", duration: "Продолжительность", date: "Дата", apply: "Оставить заявку", apply_desc: "Мы свяжемся с вами в ближайшее время", book: "Бронирование", book_desc: "Оставьте свои данные, и наши специалисты быстро свяжутся с вами.", loading: "Загрузка..." },
  visas_data: [
    { country: 'Япония', flag: '🇯🇵', price: '$150', features: ['Туристическая виза', 'До 15 дней', 'Подготовка документов', 'Запись на собеседование'] },
    { country: 'Саудовская Аравия', flag: '🇸🇦', price: '$200', features: ['Умра виза', 'Срок 1 год', 'Электронная виза', 'Быстрое оформление'] },
    { country: 'Шенген', flag: '🇪🇺', price: '$120', features: ['Туристическая виза', 'Многократная', 'Страховка', 'Сопровождение в визовый центр'] },
    { country: 'Дубай (ОАЭ)', flag: '🇦🇪', price: '$90', features: ['Электронная виза', '30 дней', 'Готово за 3 дня', 'Поручитель не нужен'] },
    { country: 'США', flag: '🇺🇸', price: '$300', features: ['Виза B1/B2', 'На 10 лет', 'Заполнение анкеты', 'Запись на собеседование'] },
    { country: 'Великобритания', flag: '🇬🇧', price: '$250', features: ['Standard Visitor', '6 месяцев', 'Перевод документов', 'Консульская регистрация'] }
  ],
  tours_data: {
    t1: { title: "Чудеса Дубая", location: "ОАЭ", days: "5 дней / 4 ночи", date: "Каждую неделю", description: "Лучшие места Дубая, Бурдж Халифа, пляж Джумейра и захватывающее сафари.", includes: ["Авиаперелет", "Отель 4*", "Завтраки", "Трансфер", "Визовая поддержка"], excludes: ["Обеды и ужины", "Личные расходы"], itinerary: [{day:1,title:"Прибытие",desc:"Встреча и размещение."}, {day:2,title:"Экскурсия",desc:"Бурдж Халифа и Dubai Mall."}, {day:3,title:"Сафари",desc:"Джип-сафари и барбекю."}, {day:4,title:"Свободный день",desc:"Отдых на пляже."}, {day:5,title:"Возвращение",desc:"Трансфер в аэропорт."}] },
    t2: { title: "Отдых в Анталии", location: "Турция", days: "7 дней / 6 ночей", date: "Июнь - Август", description: "Незабываемый отдых на Средиземноморье. Отели 5 звезд.", includes: ["Авиаперелет", "Отель 5* UAI", "Всё включено", "Трансфер", "Страховка"], excludes: ["Личные расходы", "Доп. экскурсии"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:"2-6",title:"Отдых",desc:"Свободный отдых на пляже."}, {day:7,title:"Возвращение",desc:"Вылет."}] },
    t3: { title: "Романтика Парижа", location: "Франция", days: "6 дней / 5 ночей", date: "Осень", description: "Эйфелева башня, Лувр и река Сена. Лучшее предложение для влюбленных.", includes: ["Авиаперелет", "Отель", "Экскурсия", "Визовая поддержка"], excludes: ["Питание", "Билеты в музеи"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:2,title:"Эйфелева башня",desc:"Подъем и прогулка на катере."}, {day:3,title:"Лувр",desc:"Посещение музея."}, {day:"4-5",title:"Свободный день",desc:"Шопинг."}, {day:6,title:"Возвращение",desc:"Трансфер."}] },
    t4: { title: "Пирамиды Египта", location: "Египет", days: "6 дней / 5 ночей", date: "Октябрь - Апрель", description: "Древняя история и отдых на Красном море.", includes: ["Авиаперелет", "Отель 5*", "Всё включено", "Трансфер"], excludes: ["Экскурсия в Каир", "Виза"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:2,title:"Море",desc:"Яхта и дайвинг."}, {day:3,title:"Свободный день",desc:"Экскурсия в Каир (опц.)."}, {day:4,title:"Сафари",desc:"Квадроциклы."}, {day:5,title:"Возвращение",desc:"Вылет."}] },
    t5: { title: "Умра в Мекку", location: "Саудовская Аравия", days: "14 дней / 13 ночей", date: "Каждый месяц", description: "Полный пакет для Умры. 3 дня в Медине, 10 дней в Мекке.", includes: ["Авиаперелет", "Отели", "Питание (2 раза)", "Виза", "Гид"], excludes: ["Личные расходы"], itinerary: [{day:1,title:"Медина",desc:"Мечеть Пророка."}, {day:"2-3",title:"Зияраты",desc:"Гора Ухуд."}, {day:4,title:"Мекка",desc:"Совершение Умры."}, {day:"5-13",title:"Мекка",desc:"Поклонение."}, {day:14,title:"Возвращение",desc:"Вылет."}] },
    t6: { title: "Путешествие в Стамбул", location: "Турция", days: "5 дней / 4 ночи", date: "Каждую неделю", description: "Увлекательное путешествие по историческому городу.", includes: ["Авиаперелет", "Отель 4*", "Завтрак", "Трансфер", "Экскурсия"], excludes: ["Билеты в музеи"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:2,title:"Исторический Стамбул",desc:"Айя София."}, {day:3,title:"Босфор",desc:"Круиз."}, {day:4,title:"Свободный день",desc:"Шопинг."}, {day:5,title:"Возвращение",desc:"Вылет."}] },
    t7: { title: "Тайские приключения", location: "Таиланд", days: "8 дней / 7 ночей", date: "Зима", description: "Экзотическая природа, слоны и храмы.", includes: ["Авиаперелет", "Отель", "Завтраки", "Трансфер"], excludes: ["Виза"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:"2-7",title:"Экскурсии",desc:"Острова."}, {day:8,title:"Возвращение",desc:"Вылет."}] },
    t8: { title: "Небо Каппадокии", location: "Турция", days: "4 дня / 3 ночи", date: "В сезон", description: "Отели в пещерах и полет на воздушном шаре.", includes: ["Внутренний рейс", "Пещерный отель", "Завтрак"], excludes: ["Полет на шаре"], itinerary: [{day:1,title:"Прибытие",desc:"Трансфер."}, {day:2,title:"Красный тур",desc:"Крепость Учхисар."}, {day:3,title:"Воздушный шар",desc:"Полет на шаре на рассвете."}, {day:4,title:"Возвращение",desc:"Вылет."}] },
    t9: { title: "Сингапур и Малайзия", location: "Азия", days: "8 дней / 7 ночей", date: "Каждый месяц", description: "Путешествие по самым современным городам Азии.", includes: ["Авиаперелет", "Отели 4*", "Завтраки", "Экскурсии"], excludes: ["Виза", "Личные расходы"], itinerary: [{day:1,title:"Куала-Лумпур",desc:"Встреча."}, {day:2,title:"Пещеры",desc:"Бату."}, {day:3,title:"Сингапур",desc:"Переезд."}, {day:4,title:"Марина Бэй",desc:"Сады у залива."}, {day:"5-7",title:"Свободно",desc:"Сентоза."}, {day:8,title:"Возвращение",desc:"Вылет."}] },
    t10: { title: "Приключения в Грузии", location: "Грузия", days: "6 дней / 5 ночей", date: "Весна - Осень", description: "Кавказские горы, древние церкви и вкусная еда.", includes: ["Авиаперелет", "Отель", "Завтрак", "Гид"], excludes: ["Обеды"], itinerary: [{day:1,title:"Тбилиси",desc:"Прибытие."}, {day:2,title:"Город",desc:"Прогулка."}, {day:3,title:"Казбеги",desc:"Горы Кавказа."}, {day:4,title:"Мцхета",desc:"Древняя столица."}, {day:5,title:"Свободный день",desc:"Шопинг."}, {day:6,title:"Возвращение",desc:"Трансфер."}] },
    t11: { title: "Красоты Баку", location: "Азербайджан", days: "4 дня / 3 ночи", date: "Каждый месяц", description: "Город огней - столица Азербайджана Баку.", includes: ["Авиаперелет", "Отель", "Завтрак"], excludes: ["Экскурсии"], itinerary: [{day:1,title:"Прибытие",desc:"Размещение."}, {day:2,title:"Старый город",desc:"Девичья башня."}, {day:3,title:"Баку",desc:"Огненные башни."}, {day:4,title:"Возвращение",desc:"Трансфер."}] },
    t12: { title: "Италия и Швейцария", location: "Европа", days: "9 дней / 8 ночей", date: "Лето", description: "Турне по Европе: Рим, Венеция, Милан и Альпы.", includes: ["Авиаперелет", "Отели", "Завтраки", "Поезда", "Виза"], excludes: ["Питание"], itinerary: [{day:1,title:"Рим",desc:"Прибытие."}, {day:2,title:"Колизей",desc:"Исторический Рим."}, {day:3,title:"Флоренция",desc:"Переезд."}, {day:4,title:"Венеция",desc:"Прогулка на гондоле."}, {day:5,title:"Милан",desc:"Дуомо."}, {day:"6-8",title:"Альпы",desc:"Швейцария."}, {day:9,title:"Возвращение",desc:"Вылет."}] }
  }
};

const en = {
  nav: { home: "Home", about: "About Us", tours: "Tours", contacts: "Contacts" },
  footer: { desc: "Plan your dream vacation with us. The best and affordable travel packages around the world.", links: "Quick Links", contact: "Contact", rights: "All rights reserved." },
  hero: { slide1_title: "Unforgettable journeys worldwide", slide1_sub: "Your dream vacation is now even closer", slide2_title: "Holidays in the Maldives", slide2_sub: "Crystal clear waters and white sandy beaches", slide3_title: "European Tour", slide3_sub: "A perfect blend of history and modernity", btn_more: "Details", btn_book: "Book Now" },
  tours: { subtitle: "Our Offers", title: "Weekly Tours", desc: "Explore our top-tier and affordable travel packages. Special programs tailored just for you.", from: "from", details: "More Details", load_more: "Load More", close: "Close" },
  visa: { subtitle: "Visa Services", title: "Visas Worldwide", desc: "Leave the hassle of getting a visa to us. Our professional team will prepare your documents 100% correctly.", apply: "Apply Now", load_more: "Load More", close: "Close" },
  contact: { subtitle: "Contact", title: "Get in Touch", desc: "Have questions? Our experts will be happy to assist you.", address: "Our Address", address_val: "Tashkent city, Amir Temur street 108", phone: "Phone", email: "Email", form_title: "Leave a Request", form_name: "Your Name", form_name_ph: "John Doe", form_phone: "Phone Number", form_msg: "Message", form_msg_ph: "Write your question or request...", submit: "Submit", success: "Your request has been received! We will contact you shortly." },
  detail: { premium: "Premium Tour", about: "About the Tour", includes: "Included", excludes: "Not Included", itinerary: "Daily Itinerary", gallery: "Gallery", price_title: "Tour Price", per_person: "/ per person", duration: "Duration", date: "Date", apply: "Apply Now", apply_desc: "We will get in touch with you shortly", book: "Book Now", book_desc: "Leave your details, and our experts will contact you quickly.", loading: "Loading..." },
  visas_data: [
    { country: 'Japan', flag: '🇯🇵', price: '$150', features: ['Tourist visa', 'Up to 15 days', 'Document preparation', 'Interview appointment'] },
    { country: 'Saudi Arabia', flag: '🇸🇦', price: '$200', features: ['Umrah visa', '1-year validity', 'E-visa', 'Fast processing'] },
    { country: 'Schengen', flag: '🇪🇺', price: '$120', features: ['Tourist visa', 'Multiple entry', 'Insurance coverage', 'Visa center support'] },
    { country: 'Dubai (UAE)', flag: '🇦🇪', price: '$90', features: ['E-visa', '30 days', 'Ready in 3 days', 'No sponsor required'] },
    { country: 'USA', flag: '🇺🇸', price: '$300', features: ['B1/B2 visa', '10 years', 'Application fill-up', 'Interview appointment'] },
    { country: 'UK', flag: '🇬🇧', price: '$250', features: ['Standard Visitor', '6 months', 'Document translation', 'Consular registration'] }
  ],
  tours_data: {
    t1: { title: "Wonders of Dubai", location: "UAE", days: "5 days / 4 nights", date: "Weekly", description: "Best places in Dubai, Burj Khalifa, Jumeirah beach, and an amazing desert safari.", includes: ["Flight", "4* Hotel", "Breakfast", "Transfer", "Visa support"], excludes: ["Lunches & Dinners", "Personal expenses"], itinerary: [{day:1,title:"Arrival",desc:"Meeting at the airport."}, {day:2,title:"City Tour",desc:"Burj Khalifa and Dubai Mall."}, {day:3,title:"Safari",desc:"Jeep safari and BBQ."}, {day:4,title:"Free day",desc:"Beach relaxation."}, {day:5,title:"Departure",desc:"Airport transfer."}] },
    t2: { title: "Antalya Holidays", location: "Turkey", days: "7 days / 6 nights", date: "June - August", description: "Unforgettable vacation on the Mediterranean coast. 5-star hotels.", includes: ["Flight", "5* UAI Hotel", "All-inclusive", "Transfer", "Insurance"], excludes: ["Personal expenses", "Optional tours"], itinerary: [{day:1,title:"Arrival",desc:"Check-in at hotel."}, {day:"2-6",title:"Relaxation",desc:"Free days at the beach."}, {day:7,title:"Departure",desc:"Flight back."}] },
    t3: { title: "Romantic Paris", location: "France", days: "6 days / 5 nights", date: "Autumn", description: "Eiffel Tower, Louvre, and Seine river. The best offer for couples.", includes: ["Flight", "Hotel", "Excursions", "Visa support"], excludes: ["Meals", "Museum tickets"], itinerary: [{day:1,title:"Arrival",desc:"Check-in."}, {day:2,title:"Eiffel Tower",desc:"Tower visit & cruise."}, {day:3,title:"Louvre",desc:"Museum tour."}, {day:"4-5",title:"Free day",desc:"Shopping."}, {day:6,title:"Departure",desc:"Airport transfer."}] },
    t4: { title: "Pyramids of Egypt", location: "Egypt", days: "6 days / 5 nights", date: "Oct - April", description: "Ancient history and Red Sea relaxation.", includes: ["Flight", "5* Hotel", "All inclusive", "Transfer"], excludes: ["Cairo tour", "Visa"], itinerary: [{day:1,title:"Arrival",desc:"Check-in."}, {day:2,title:"Sea",desc:"Yacht and diving."}, {day:3,title:"Free day",desc:"Optional Cairo tour."}, {day:4,title:"Safari",desc:"Quad bikes."}, {day:5,title:"Departure",desc:"Flight."}] },
    t5: { title: "Umrah to Mecca", location: "Saudi Arabia", days: "14 days / 13 nights", date: "Monthly", description: "Full package for Umrah. 3 days in Medina, 10 days in Mecca.", includes: ["Flight", "Hotels", "Half-board", "Visa", "Guide"], excludes: ["Personal expenses"], itinerary: [{day:1,title:"Medina",desc:"Prophet's Mosque."}, {day:"2-3",title:"Ziyarat",desc:"Mount Uhud."}, {day:4,title:"Mecca",desc:"Umrah performance."}, {day:"5-13",title:"Mecca",desc:"Worship and prayers."}, {day:14,title:"Departure",desc:"Flight back."}] },
    t6: { title: "Journey to Istanbul", location: "Turkey", days: "5 days / 4 nights", date: "Weekly", description: "Amazing trip through the historical city.", includes: ["Flight", "4* Hotel", "Breakfast", "Transfer", "Tours"], excludes: ["Museum tickets"], itinerary: [{day:1,title:"Arrival",desc:"Check-in."}, {day:2,title:"Historical Istanbul",desc:"Hagia Sophia."}, {day:3,title:"Bosphorus",desc:"Cruise."}, {day:4,title:"Free day",desc:"Shopping at Grand Bazaar."}, {day:5,title:"Departure",desc:"Transfer."}] },
    t7: { title: "Thai Adventures", location: "Thailand", days: "8 days / 7 nights", date: "Winter", description: "Exotic nature, elephants, and temples.", includes: ["Flight", "Hotel", "Breakfast", "Transfer"], excludes: ["Visa"], itinerary: [{day:1,title:"Arrival",desc:"Check-in."}, {day:"2-7",title:"Tours",desc:"Island hopping."}, {day:8,title:"Departure",desc:"Flight."}] },
    t8: { title: "Sky of Cappadocia", location: "Turkey", days: "4 days / 3 nights", date: "Seasonal", description: "Cave hotels and unforgettable hot air balloon flights.", includes: ["Domestic flight", "Cave hotel", "Breakfast"], excludes: ["Balloon flight"], itinerary: [{day:1,title:"Arrival",desc:"Transfer."}, {day:2,title:"Red Tour",desc:"Uchisar Castle."}, {day:3,title:"Hot Air Balloon",desc:"Flight at dawn."}, {day:4,title:"Departure",desc:"Transfer."}] },
    t9: { title: "Singapore & Malaysia", location: "Asia", days: "8 days / 7 nights", date: "Monthly", description: "Journey across modern Asian cities.", includes: ["Flight", "4* Hotels", "Breakfast", "Tours"], excludes: ["Visa", "Personal expenses"], itinerary: [{day:1,title:"Kuala Lumpur",desc:"Arrival."}, {day:2,title:"Caves",desc:"Batu Caves."}, {day:3,title:"Singapore",desc:"Transfer."}, {day:4,title:"Marina Bay",desc:"Gardens by the Bay."}, {day:"5-7",title:"Free day",desc:"Sentosa."}, {day:8,title:"Departure",desc:"Flight."}] },
    t10: { title: "Adventures in Georgia", location: "Georgia", days: "6 days / 5 nights", date: "Spring - Autumn", description: "Caucasus mountains, ancient churches, and delicious food.", includes: ["Flight", "Hotel", "Breakfast", "Guide"], excludes: ["Lunches/Dinners"], itinerary: [{day:1,title:"Tbilisi",desc:"Arrival."}, {day:2,title:"City",desc:"Old town tour."}, {day:3,title:"Kazbegi",desc:"Mountains."}, {day:4,title:"Mtskheta",desc:"Ancient capital."}, {day:5,title:"Free day",desc:"Shopping."}, {day:6,title:"Departure",desc:"Transfer."}] },
    t11: { title: "Beauty of Baku", location: "Azerbaijan", days: "4 days / 3 nights", date: "Monthly", description: "City of winds - Baku.", includes: ["Flight", "Hotel", "Breakfast"], excludes: ["Excursions"], itinerary: [{day:1,title:"Arrival",desc:"Check-in."}, {day:2,title:"Old City",desc:"Maiden Tower."}, {day:3,title:"Baku",desc:"Flame Towers."}, {day:4,title:"Departure",desc:"Transfer."}] },
    t12: { title: "Italy & Switzerland", location: "Europe", days: "9 days / 8 nights", date: "Summer", description: "European tour: Rome, Venice, Milan, and the Alps.", includes: ["Flight", "Hotels", "Breakfast", "Trains", "Visa"], excludes: ["Meals"], itinerary: [{day:1,title:"Rome",desc:"Arrival."}, {day:2,title:"Colosseum",desc:"History."}, {day:3,title:"Florence",desc:"Train ride."}, {day:4,title:"Venice",desc:"Gondola ride."}, {day:5,title:"Milan",desc:"Duomo."}, {day:"6-8",title:"Alps",desc:"Swiss views."}, {day:9,title:"Departure",desc:"Flight."}] }
  }
};

fs.mkdirSync('./src/locales', { recursive: true });
fs.writeFileSync('./src/locales/uz.json', JSON.stringify(uz, null, 2));
fs.writeFileSync('./src/locales/ru.json', JSON.stringify(ru, null, 2));
fs.writeFileSync('./src/locales/en.json', JSON.stringify(en, null, 2));

console.log("Locales generated!");
